<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.airlift.test</groupId>
    <artifactId>generated-client-compatibility</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>generated-client-compatibility</name>
    <description>Standalone API Builder to generated HTTP client compatibility scenario</description>

    <properties>
        <dep.airlift.version>@project.version@</dep.airlift.version>
        <dep.assertj.version>3.27.6</dep.assertj.version>
        <dep.guice.version>7.0.0</dep.guice.version>
        <dep.junit.version>6.0.3</dep.junit.version>
        <dep.openapi-generator.version>@dep.openapi-generator.version@</dep.openapi-generator.version>
        <maven.compiler.release>25</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>api</artifactId>
            <version>${dep.airlift.version}</version>
        </dependency>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>bootstrap</artifactId>
            <version>${dep.airlift.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>configuration</artifactId>
            <version>${dep.airlift.version}</version>
        </dependency>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>http-client</artifactId>
            <version>${dep.airlift.version}</version>
        </dependency>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>http-server</artifactId>
            <version>${dep.airlift.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>jaxrs</artifactId>
            <version>${dep.airlift.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>json</artifactId>
            <version>${dep.airlift.version}</version>
        </dependency>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>node</artifactId>
            <version>${dep.airlift.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>${dep.guice.version}</version>
            <classifier>classes</classifier>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${dep.assertj.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${dep.junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${dep.junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.6</version>
            </plugin>
            <plugin>
                <groupId>io.airlift</groupId>
                <artifactId>api-maven-plugin</artifactId>
                <version>${dep.airlift.version}</version>
                <executions>
                    <execution>
                        <id>generate-openapi</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>generate-openapi</goal>
                        </goals>
                        <configuration>
                            <serviceClasses>
                                <serviceClass>io.airlift.openapi.client.compatibility.FrameService</serviceClass>
                                <serviceClass>io.airlift.openapi.client.compatibility.StatusService</serviceClass>
                            </serviceClasses>
                            <serviceTypeClass>io.airlift.openapi.client.compatibility.CompatibilityServiceType</serviceTypeClass>
                            <securityScheme>BEARER_ACCESS_TOKEN</securityScheme>
                            <outputFile>${project.build.directory}/openapi.json</outputFile>
                            <prettyPrint>true</prettyPrint>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${dep.openapi-generator.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>io.airlift</groupId>
                        <artifactId>http-client-generator</artifactId>
                        <version>${dep.airlift.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>generate-airlift-client</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.build.directory}/openapi.json</inputSpec>
                            <generatorName>airlift-http-client</generatorName>
                            <apiPackage>io.airlift.openapi.client.generated.api</apiPackage>
                            <modelPackage>io.airlift.openapi.client.generated.model</modelPackage>
                            <invokerPackage>io.airlift.openapi.client.generated</invokerPackage>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <sourceFolder>/</sourceFolder>
                                <projectName>compatibility</projectName>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-second-airlift-client</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.build.directory}/openapi.json</inputSpec>
                            <generatorName>airlift-http-client</generatorName>
                            <apiPackage>io.airlift.openapi.client.generated.second.api</apiPackage>
                            <modelPackage>io.airlift.openapi.client.generated.second.model</modelPackage>
                            <invokerPackage>io.airlift.openapi.client.generated.second</invokerPackage>
                            <output>${project.build.directory}/generated-sources/openapi-second</output>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <sourceFolder>/</sourceFolder>
                                <projectName>compatibility-second</projectName>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <id>add-generated-client-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/openapi</source>
                                <source>${project.build.directory}/generated-sources/openapi-second</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
