changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: Improvements 🎉
      labels:
        - improvement
    - title: Dependency updates 📦
      labels:
        - dependency
    - title: Others
      labels:
        - "*"
