changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Improvements 🎉
      labels:
        - improvement
        - cleanup
    - title: Dependency updates 📦
      labels:
        - dependency
    - title: Security fixes 🔒
      labels:
        - security
    - title: Others
      labels:
        - "*"
