/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.airlift.http.client.generator;

import io.takari.maven.testing.TestResources5;
import io.takari.maven.testing.executor.MavenRuntime;
import io.takari.maven.testing.executor.MavenRuntime.MavenRuntimeBuilder;
import io.takari.maven.testing.executor.MavenVersions;
import io.takari.maven.testing.executor.junit.MavenPluginTest;
import org.junit.jupiter.api.extension.RegisterExtension;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;

import static java.lang.System.getProperty;
import static java.util.Objects.requireNonNull;
import static org.assertj.core.api.Assertions.assertThat;

@MavenVersions("3.9.14")
class EndToEndIntegrationTest
{
    @RegisterExtension
    final TestResources5 resources = new TestResources5();

    private final MavenRuntime maven;

    EndToEndIntegrationTest(MavenRuntimeBuilder mavenBuilder)
            throws Exception
    {
        this.maven = mavenBuilder
                .withCliOptions(
                        "-B",
                        "-U",
                        "-Ddep.airlift.version=" + requireNonNull(getProperty("project.version"), "project.version system property is null"))
                .build();
    }

    @MavenPluginTest
    void testEndToEndClientGeneration()
            throws Exception
    {
        File basedir = resources.getBasedir("widget-service");

        maven.forProject(basedir)
                .execute("clean", "test-compile")
                .assertErrorFreeLog();

        // Verify OpenAPI spec was generated
        File specFile = new File(basedir, "target/openapi.json");
        assertThat(specFile)
                .describedAs("OpenAPI spec should be generated by api-maven-plugin")
                .exists();
        String specContent = Files.readString(specFile.toPath());
        assertThat(specContent).contains("\"openapi\"");
        assertThat(specContent).contains("\"paths\"");

        // Verify generated client directory
        Path generatedDir = basedir.toPath().resolve("target/generated-sources/openapi/io/airlift/test/generated");

        // Verify client classes (named *Client, not *Api)
        Path widgetsClient = generatedDir.resolve("api/WidgetsServiceClient.java");
        assertThat(widgetsClient).exists();
        String widgetsClientContent = Files.readString(widgetsClient);
        assertThat(widgetsClientContent).contains("public class WidgetsServiceClient");
        assertThat(widgetsClientContent).contains("private final HttpClient httpClient");
        assertThat(widgetsClientContent).contains("private final URI baseUri");
        assertThat(widgetsClientContent).contains("@Inject");

        // Verify static final codecs
        assertThat(widgetsClientContent).contains("private static final JsonCodec<");
        assertThat(widgetsClientContent).contains("jsonCodec(");

        // Verify inline request building (no intermediary)
        assertThat(widgetsClientContent).contains("uriBuilderFrom(baseUri)");
        assertThat(widgetsClientContent).contains("httpClient.execute(");
        assertThat(widgetsClientContent).contains("createJsonResponseHandler(");

        // Verify retry-wrapped execution with RetryPolicy
        assertThat(widgetsClientContent).contains("retryPolicy.execute(");
        assertThat(widgetsClientContent).contains("private final RetryPolicy retryPolicy");

        // Verify CRUD methods
        assertThat(widgetsClientContent).contains("listWidget");
        assertThat(widgetsClientContent).contains("createWidget");
        assertThat(widgetsClientContent).contains("getWidget");
        assertThat(widgetsClientContent).contains("deleteWidget");
        assertThat(widgetsClientContent).contains("updateWidget");

        // Verify query parameter handling via HttpUriBuilder
        assertThat(widgetsClientContent).contains("addParameter(");
        assertThat(widgetsClientContent).contains("pageToken");
        assertThat(widgetsClientContent).contains("pageSize");
        assertThat(widgetsClientContent).contains("orderBy");

        Path itemsClient = generatedDir.resolve("api/ItemsServiceClient.java");
        assertThat(itemsClient)
                .describedAs("ItemsServiceClient should be generated for polymorphic operations")
                .exists();
        assertThat(Files.readString(itemsClient)).contains("public class ItemsServiceClient");

        // Verify models
        Path modelDir = generatedDir.resolve("model");
        assertThat(modelDir.resolve("Widget.java")).exists();
        assertThat(Files.readString(modelDir.resolve("Widget.java"))).contains("widgetId");
        assertThat(modelDir.resolve("NewWidget.java")).exists();
        assertThat(modelDir.resolve("WidgetPatch.java")).exists();

        Path paginatedWidget = modelDir.resolve("PaginatedWidget.java");
        assertThat(paginatedWidget).exists();
        String paginatedContent = Files.readString(paginatedWidget);
        assertThat(paginatedContent).contains("nextPageToken");
        assertThat(paginatedContent).contains("result");

        // Verify polymorphic Item models
        assertThat(modelDir.resolve("Item.java")).exists();
        assertThat(modelDir.resolve("ItemBook.java")).exists();
        assertThat(modelDir.resolve("ItemMovie.java")).exists();

        // Verify supporting infrastructure
        Path clientModule = generatedDir.resolve("ApiClientModule.java");
        assertThat(clientModule).exists();
        String moduleContent = Files.readString(clientModule);
        assertThat(moduleContent).contains("implements Module");
        assertThat(moduleContent).contains("WidgetsServiceClient.class");
        assertThat(moduleContent).contains("ItemsServiceClient.class");

        Path clientConfig = generatedDir.resolve("ApiClientConfig.java");
        assertThat(clientConfig).exists();
        String configContent = Files.readString(clientConfig);
        assertThat(configContent).contains("@Config");
        assertThat(configContent).doesNotContain("@ConfigDescription");

        Path annotation = generatedDir.resolve("ForApi.java");
        assertThat(annotation).exists();
        assertThat(Files.readString(annotation)).contains("@BindingAnnotation");

        assertThat(generatedDir.resolve("ApiException.java")).exists();
        assertThat(Files.readString(generatedDir.resolve("ApiException.java")))
                .contains("extends RuntimeException");
    }
}
